-- MySQL Script generated by MySQL Workbench
-- Tue Jul  6 21:31:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ggdabhmy_carmax168
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ggdabhmy_carmax168
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ggdabhmy_carmax168` DEFAULT CHARACTER SET utf8 ;
USE `ggdabhmy_carmax168` ;

-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`managers` (
  `manager_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `password` CHAR(255) NOT NULL,
  `privilege` VARCHAR(45) NOT NULL COMMENT '1: admin (老闆)\n2: vice-admin (副老闆)\n3: manager (員工)',
  `active` VARCHAR(45) NOT NULL COMMENT 'Active = 1, not active = 0',
  PRIMARY KEY (`manager_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`subscribed_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`subscribed_users` (
  `email` VARCHAR(45) NULL,
  `sid` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`info_feeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`info_feeds` (
  `nid` INT NOT NULL AUTO_INCREMENT,
  `news_date` DATE NULL COMMENT '20210630',
  `news_title` VARCHAR(45) NOT NULL COMMENT 'e.g. 簽署永續績效連結貸款 中信銀攜潤、星能 落實綠色金融',
  `news_publisher` VARCHAR(45) NULL COMMENT 'e.g. 工商時報',
  `news_journalist` VARCHAR(45) NULL COMMENT 'E.g. 魏喬怡／台北報導',
  `news_citation` VARCHAR(45) NULL COMMENT '新聞的原文出處, e.g. https://autos.udn.com/autos/story/7826/5171290',
  `news_type` VARCHAR(45) NULL COMMENT '1 - information\n2 - success story\n3 - news report',
  PRIMARY KEY (`nid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`info_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`info_contents` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `nid` INT NOT NULL COMMENT 'On update cascade, on delete restrict.',
  `content_order` INT NOT NULL,
  `content` VARCHAR(500) NOT NULL COMMENT 'Could be image filepath, or a paragraph',
  `content_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cid`),
  INDEX `fid_idx` (`nid` ASC),
  CONSTRAINT `nid_infoContent`
    FOREIGN KEY (`nid`)
    REFERENCES `ggdabhmy_carmax168`.`info_feeds` (`nid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`QA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`QA` (
  `qid` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1000) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `subscribed` VARCHAR(45) NOT NULL,
  `postedTime` DATETIME NOT NULL COMMENT 'YYYY-MM-DD hh:mm:ss',
  `answer` VARCHAR(1000) NULL,
  `answerTime` DATETIME NULL,
  `answerer_id` INT NULL,
  PRIMARY KEY (`qid`),
  INDEX `manager_id_idx` (`answerer_id` ASC),
  CONSTRAINT `answerer_id_QA`
    FOREIGN KEY (`answerer_id`)
    REFERENCES `ggdabhmy_carmax168`.`managers` (`manager_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`QA_follow_ups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`QA_follow_ups` (
  `fid` INT NOT NULL AUTO_INCREMENT,
  `qid` INT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `postedTime` DATETIME NOT NULL,
  PRIMARY KEY (`fid`),
  INDEX `fid_idx` (`qid` ASC),
  CONSTRAINT `fid_QAFollowUps`
    FOREIGN KEY (`qid`)
    REFERENCES `ggdabhmy_carmax168`.`QA` (`qid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`loan_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`loan_reference` (
  `loan_type` INT NOT NULL AUTO_INCREMENT,
  `loan_description` VARCHAR(45) NOT NULL,
  `is_type` INT NOT NULL,
  PRIMARY KEY (`loan_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`loan_to_page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`loan_to_page` (
  `page_id` INT NOT NULL AUTO_INCREMENT,
  `loan_type` INT NOT NULL,
  PRIMARY KEY (`page_id`),
  INDEX `loan_type_idx` (`loan_type` ASC),
  CONSTRAINT `loan_type_loanToPage`
    FOREIGN KEY (`loan_type`)
    REFERENCES `ggdabhmy_carmax168`.`loan_reference` (`loan_type`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`loan_page_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`loan_page_content` (
  `content_id` INT NOT NULL AUTO_INCREMENT,
  `page_id` INT NOT NULL,
  `content_type` VARCHAR(45) NOT NULL,
  `content_order` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  PRIMARY KEY (`content_id`),
  INDEX `page_id_idx` (`page_id` ASC),
  CONSTRAINT `page_id_loanPageContent`
    FOREIGN KEY (`page_id`)
    REFERENCES `ggdabhmy_carmax168`.`loan_to_page` (`page_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ggdabhmy_carmax168`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ggdabhmy_carmax168`.`form` (
  `form_id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NOT NULL,
  `car_plate_num` VARCHAR(45) NULL,
  `model_year` VARCHAR(45) NULL,
  `loan_type` INT NOT NULL,
  `occupation` VARCHAR(45) NULL,
  `convenienceTime` VARCHAR(45) NULL,
  `note` VARCHAR(500) NULL,
  PRIMARY KEY (`form_id`),
  INDEX `loan_type_idx` (`loan_type` ASC),
  CONSTRAINT `loan_type_form`
    FOREIGN KEY (`loan_type`)
    REFERENCES `ggdabhmy_carmax168`.`loan_reference` (`loan_type`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
